name: Build and publish Docker image

on:
  push:
    branches:
      - "main"
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set release tag
        id: vars
        run: |
          TAG_NAME=${{github.ref_name}}
          echo "tag=${TAG_NAME/main/latest}" >> $GITHUB_OUTPUT

      - name: Print release tag
        run: |
          echo Building Docker images with tag: ${{ steps.vars.outputs.tag }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Perceiver IO Docker image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
